# Generated by Django 5.2 on 2025-04-16 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='imagem',
            field=models.ImageField(blank=True, null=True, upload_to='recetas/'),
        ),
    ]
