# Generated by Django 5.2 on 2025-04-17 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_receitas_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='receitas',
            old_name='descricão',
            new_name='descricao',
        ),
        migrations.AlterField(
            model_name='receitas',
            name='ingredientes',
            field=models.TextField(),
        ),
    ]
