# Generated by Django 5.2 on 2025-04-22 23:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_descricão_receitas_descricao_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='receitas',
            name='video_url',
            field=models.URLField(blank=True, help_text='Insira a URL do videdo de preparo (Youtube, etc.)', null=True),
        ),
        migrations.AlterField(
            model_name='receitas',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
