# Generated by Django 5.2 on 2025-04-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_receitas_video_url_alter_receitas_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receitas',
            name='descricao',
            field=models.TextField(max_length=300),
        ),
    ]
